corelli = {'Facility': 'SNS',
           'Name': 'CORELLI',
           'Wavelength': [0.6, 2.5],
           'Goniometer': {'BL9:Mot:Sample:Axis1': [0, 1, 0, 1],
                          'BL9:Mot:Sample:Axis2': [0, 1, 0, 1],
                          'BL9:Mot:Sample:Axis3': [0, 1, 0, 1]},
           'GoniometerEntry': 'metadata.entry.daslogs',
           'Scale': 'metadata.entry.proton_charge',
           'Title': 'metadata.entry.title',
           'RunNumber': 'metadata.entry.run_number',
           'Extension': '.nxs.h5'}

topaz = {'Facility': 'SNS',
         'Name': 'TOPAZ',
         'Wavelength': [0.4, 3.5],
         'Goniometer': {'BL12:Mot:goniokm:omega': [0, 1, 0, 1],
                        'BL12:Mot:goniokm:chi': [0, 0, 1, 1],
                        'BL12:Mot:goniokm:phi': [0, 1, 0, 1]},
         'GoniometerEntry': 'metadata.entry.daslogs',
         'Scale': 'metadata.entry.proton_charge',
         'Title': 'metadata.entry.title',
         'RunNumber': 'metadata.entry.run_number',
         'Extension': '.nxs.h5'}

mandi = {'Facility': 'SNS',
         'Name': 'MANDI',
         'Wavelength': [2, 4],
         'Goniometer': {'BL11B:Mot:omega': [0, 1, 0, 1],
                        'BL11B:Mot:chi': [0, 0, 1, 1],
                        'BL11B:Mot:phi': [0, 1, 0, 1]},
         'GoniometerEntry': 'metadata.entry.daslogs',
         'Scale': 'metadata.entry.proton_charge',
         'Title': 'metadata.entry.title',
         'RunNumber': 'metadata.entry.run_number',
         'Extension': '.nxs.h5'}

wand2 = {'Facility': 'HFIR',
         'Name': 'HB2C',
         'InstrumentName': 'WAND',
         'FancyName': 'WAND²',
         'Wavelength': 1.486,
         'Goniometer': {'HB2C:Mot:sgl': [1, 0, 0, -1],
                        'HB2C:Mot:sgu': [0, 0, 1, -1],
                        'HB2C:Mot:s1': [0, 1, 0, 1]},
         'GoniometerAxisNames': ['s1'],
         'GoniometerEntry': 'metadata.entry.daslogs',
         'Scale': 'metadata.entry.duration',
         'Title': 'metadata.entry.title',
         'RunNumber': 'metadata.entry.run_number',
         'Extension': '.nxs.h5'}

demand = {'Facility': 'HFIR',
          'Name': 'HB3A',
          'FancyName': 'DEMAND',
          'Wavelength': 1.546,
          'Goniometer': {'omega': [0, 1, 0, -1],
                         'chi': [0, 0, 1, -1],
                         'phi': [0, 1, 0, -1]},
          'GoniometerEntry': 'statistics',
          'Scale': 'statistics.time',
          'Title': 'metadata.scan_title',
          'RunNumber': 'metadata.scan',
          'Extension': '.dat'}
